Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - Gemfile

Rails/FilePath:
  Exclude:
    - config/application.rb
LineLength:
  Exclude:
    - config/environments/*
    - config/initializers/*
  Max: 120
  IgnoreCopDirectives: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 36

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 8

Rails/SkipsModelValidations:
  Enabled: false
