Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - Gemfile

Style/Lambda:
  Enabled: false

Rails/FilePath:
  Exclude:
    - config/application.rb

LineLength:
  Exclude:
    - config/environments/*
    - config/initializers/*
  Max: 139
  IgnoreCopDirectives: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 62

Metrics/MethodLength:
  Max: 33

Metrics/CyclomaticComplexity:
  Max: 8

Rails/SkipsModelValidations:
  Enabled: false

Metrics/ClassLength:
  Max: 134

Style/SymbolArray:
  Enabled: false
