version: 2

jobs:
  build:
    working_directory: ~/convection
    docker:
      - image: artsy/ruby:2.5.1-node-chrome
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:10.1-alpine
    steps:
      - checkout

      - type: cache-restore
        key: convection-bundler-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: convection-bundler-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: chromedriver-update 2.37

      - run: mv config/database{.circle,}.yml
      - run: bundle exec rake db:create db:migrate
      - run: bundle exec rake

  deploy-staging:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/convection-staging.git $CIRCLE_SHA1:master

  deploy-production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/convection-production.git $CIRCLE_SHA1:master


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: release
