---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: convection-rubyrep
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: convection
        component: rubyrep
        layer: data
      name: convection-rubyrep
    spec:
      containers:
        - name: rubyrep-convection
          image: artsy/rubyrep
          args: ["/rubyrep-2.0.1/rubyrep", "--verbose", "replicate", "-c", "/mnt/default.conf"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: rubyrep-convection
              mountPath: /mnt/default.conf
              subPath: default.conf
      volumes:
        - name: rubyrep-convection
          configMap:
            name: rubyrep-convection
